# Generated by Django 5.0.2 on 2024-02-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile/images"),
        ),
    ]
